FROM node:20.18.0-alpine

WORKDIR /app

# 1. Copia solo los archivos de dependencias
COPY package.json package-lock.json* ./

# 2. Instala las dependencias (esto se cacheará)
RUN npm install

# 3. Define el comando (no se necesita COPY . .)
CMD ["npm", "run", "dev"]